package com.lw.common.orgcode;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * CodeCheckServiceService service = new CodeCheckServiceService();
 * CodeCheckServiceDelegate portType = service.getCodeCheckServicePort();
 * portType.searchKEY(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "CodeCheckServiceService", targetNamespace = "http://wsserver.codeck.cncait.com/", wsdlLocation = "http://codeplat.cnca.cn/codecheckws/CodeCheckServicePort?wsdl")
public class CodeCheckServiceService extends Service {

	private final static URL CODECHECKSERVICESERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(CodeCheckServiceService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = CodeCheckServiceService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://codeplat.cnca.cn/codecheckws/CodeCheckServicePort?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://codeplat.cnca.cn/codecheckws/CodeCheckServicePort?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		CODECHECKSERVICESERVICE_WSDL_LOCATION = url;
	}

	public CodeCheckServiceService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public CodeCheckServiceService() {
		super(CODECHECKSERVICESERVICE_WSDL_LOCATION,
				new QName("http://wsserver.codeck.cncait.com/",
						"CodeCheckServiceService"));
	}

	/**
	 * 
	 * @return returns CodeCheckServiceDelegate
	 */
	@WebEndpoint(name = "CodeCheckServicePort")
	public CodeCheckServiceDelegate getCodeCheckServicePort() {
		return super.getPort(new QName("http://wsserver.codeck.cncait.com/",
				"CodeCheckServicePort"), CodeCheckServiceDelegate.class);
	}

}
