package com.lw.common.orgcode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "CodeCheckServiceDelegate", targetNamespace = "http://wsserver.codeck.cncait.com/")
public interface CodeCheckServiceDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "searchKEY", targetNamespace = "http://wsserver.codeck.cncait.com/", className = "com.common.webservice.orgcode.SearchKEY")
	@ResponseWrapper(localName = "searchKEYResponse", targetNamespace = "http://wsserver.codeck.cncait.com/", className = "com.common.webservice.orgcode.SearchKEYResponse")
	public String searchKEY(
			@WebParam(name = "arg0", targetNamespace = "") QueryCondition arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.cncait.client.QueryResult
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "searchDMInfo", targetNamespace = "http://wsserver.codeck.cncait.com/", className = "com.common.webservice.orgcode.SearchDMInfo")
	@ResponseWrapper(localName = "searchDMInfoResponse", targetNamespace = "http://wsserver.codeck.cncait.com/", className = "com.common.webservice.orgcode.SearchDMInfoResponse")
	public QueryResult searchDMInfo(
			@WebParam(name = "arg0", targetNamespace = "") QueryCondition arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "postOrgInfo", targetNamespace = "http://wsserver.codeck.cncait.com/", className = "com.common.webservice.orgcode.PostOrgInfo")
	@ResponseWrapper(localName = "postOrgInfoResponse", targetNamespace = "http://wsserver.codeck.cncait.com/", className = "com.common.webservice.orgcode.PostOrgInfoResponse")
	public String postOrgInfo(
			@WebParam(name = "arg0", targetNamespace = "") QueryCondition arg0,
			@WebParam(name = "arg1", targetNamespace = "") OrgInfo arg1);

}
